### ISSUE TITLE
Pre commit hook showing entire git diff and no errors when there are

### ISSUE THREAD

**Issue by pottink** [phpro/grumphp#992] opened 2022-03-11 11:48 UTC
![image](https://user-images.githubusercontent.com/2572887/157861192-6cdcc221-4c7e-4920-aa77-49f324e124b9.png)

When I execute my pre-commit-hook to run the GrumPHP tests, it always shows me all the git diff output and if there are errors, it just quits with no message or errors shown.

Anyone else having this issue?

When I manually run the GrumPHP it does everything as wanted.

PHP: 8.0.12
GrumPHP Shim: 1.8.1

pre-commit:
```
#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

# Fetch the GIT diff and format it as command input:
DIFF=$(git -c diff.mnemonicprefix=false -c diff.noprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged | cat)

# Grumphp env vars

export GRUMPHP_GIT_WORKING_DIR="$(git rev-parse --show-toplevel)"

# Run GrumPHP
(cd "./" && printf "%s\n" "${DIFF}" | kevin app 'vendor/phpro/grumphp-shim/grumphp' 'git:pre-commit' '--skip-success-output')
```

**Comment by veewee** [comment] 2022-03-25 12:49
Spent the afternoon investigating this issue - since members on our team have similar issues.
I've made sure to have to same versions of git, docker, docker-compose, ... locally.
I've compared environment vars, terminals, git configs, ...
Still not able to reproduce.

My findings:

```
printf "%s\n" "${DIFF}" | docker-compose run --rm --no-deps application php 'vendor/bin/grumphp' 'git:pre-commit'
```

Piping the input to docker-compose is where it goes wrong:

* If you run the command `printf "%s\n" "${DIFF}" | php 'vendor/bin/grumphp' 'git:pre-commit'` directly on the container, it works as expected
* If you add `-T` option (without TTY) to the docker-compose run command, grumphp is executed - but the output is not visible.
* When using docker-compose exec instead of run, it also does not do the trick.
* If you use grumphp without printf-ing the diff into docker-compose, it does work (yet this is not correct, since it won't run on partial commits)

Some assumptions:

* It is not docker-composer version related, since it works or fails on both 1&2 depending on your system
* printf should be stable amongst all shells

My bet guess is that it can be fixed with some shell environment variable that I dont know of.

**Comment by garciasdos** [comment] 2022-03-30 09:28
Same error happening here, solved with the temporary solution provided by @veewee. But hoping this is fixed in a future version 🙏🏼

**Comment by veewee** [comment] 2022-03-30 09:40
@garciasdos The problem is not in GrumPHP itself, but in docker-compose. The *permanent* solution is to use the -T flag inside the commit hook:

```
EXEC_GRUMPHP_COMMAND: docker-compose run -T [YOUROTHERPARAMS]
```

(when changing this env var, you'll need to rerun `grumphp git:init` in order for the changes to be written to the hook file)

---

As mentioned above: previously docker-compose did a check if it is running in a TTY console or not.
This check got removed. If you are using some custom tooling like @pottink's `kevin`, you can add a check to see if your running in a TTY or pipe yourself.
In bash, this would look like this:

```
USETTY=""

# Check if stdin is attached a pipe or a redirect
if [[ -p /dev/stdin ]] || [[ ! -t 0 && ! -p /dev/stdin ]]; then
  USETTY="-T"
fi

# Check if stdout is attached a pipe or a redirect
if [[ -p /dev/stdout ]] || [[ ! -t 1 && ! -p /dev/stdout ]]; then
  USETTY="-T"
fi

docker-compose run $USETTY --rm "${APP_NAME}" "$@"
```

**Closed** 2022-04-06 11:43 UTC
Labels: question
