### ISSUE TITLE
Installing when grumphp.yml is not created or is empty causes warnings

### ISSUE THREAD

**Issue by aderuwe** [phpro/grumphp#2] opened 2015-03-19 08:55 UTC
```
Writing lock file
Generating autoload files

Warning: array_key_exists() expects parameter 2 to be array, null given in vendor/phpro/grumphp/src/GrumPHP/Configuration/TaskCompilerPass.php on line 27
```

**Comment by aderuwe** [comment] 2015-03-19 08:57
It also means that the bin dir might be set to the default incorrectly.

**Comment by veewee** [comment] 2015-03-19 15:26
The warning is fixed in master. The paths are still an issue.

**Comment by veewee** [comment] 2015-03-19 17:00
First part of the issue is fixed, the other part will be solved by #4.

**Closed by veewee** 2015-03-19 17:00 UTC
