### ISSUE TITLE
Move EXEC_GRUMPHP_COMMAND to composer

### ISSUE THREAD

**Issue by erikseifert** [phpro/grumphp#783] opened 2020-07-06 14:26 UTC
| Q               | A
| --------------- | ---
| Version         | 0.15.2
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | 

Is would be great to have the possibility to specify EXEC_GRUMPHP_COMMAND in composer. 

```json
"extra": {
  "grumphp": {
     "exec-grumphp-command": "fin exec php"
  }
}
```
We are using docksal, so we can specify the execution directly in composer for local development.

**Comment by veewee** [comment] 2020-07-09 05:31
Duplicate of https://github.com/phpro/grumphp/issues/676

I would put it in the grumphp.yaml file instead of inside the composer file.

**Closed by veewee** 2020-07-09 05:31 UTC
