### ISSUE TITLE
phpstan not showing errors

### ISSUE THREAD

**Issue by talhaamir4130** [phpro/grumphp#1050] opened 2022-10-28 06:12 UTC
| Q               | A
| --------------- | ---
| Version         | `0.19.1`
| Bug?            | yes
| New feature?    | no
| Question?       | yes
| Documentation?  | no

**My configuration**
```
grumphp:
    hooks_preset: local
    process_timeout: 600
    fixer:
        enabled: true
        fix_by_default: true
    parallel:
        enabled: true
        max_workers: 32
    tasks:
        phpcsfixer:
            verbose: false
            rules: ['@PSR1', '@PSR2', '@Symfony', '@PhpCsFixer', -concat_space]
        phpstan:
            configuration: './phpstan.neon'

```

phpstan file config:
```
parameters:
  level: 7
  reportUnmatchedIgnoredErrors: false
  checkGenericClassInNonGenericObjectType: false
  paths:
    - "%rootDir%/../../../src"
    - "%rootDir%/../../../tests"
  excludePaths:
    - "%rootDir%/../../../tests/features"
    - "%rootDir%/../../../var"
```

phpstan config location is `project/phpstan.neon`

When I run `vendor/bin/phpstan analyse src tests` I see errors, but when I run `vendor/bin/grumphp run` I don't see any phpstan errors

![Screenshot from 2022-10-28 11-19-13](https://user-images.githubusercontent.com/18555977/198517053-391207fa-48fd-4c46-8933-43d58219fb20.png)

![Screenshot from 2022-10-28 11-20-32](https://user-images.githubusercontent.com/18555977/198517271-2483597d-ecb8-4f70-a462-b4ae9af5379c.png)

**Comment by veewee** [comment] 2022-10-28 06:23
Hello,

Can you try it out with latest grumphp version? The one you are using is quite old...
What are the paths in phpstan? Are they included in git? Because it seems like they are going out of the root of your prohect at first sight?

**Comment by veewee** [comment] 2022-12-20 13:36
Closing this one for now.
Feel free to reopen if you are able to reproduce with a newer version of GrumPHP.

**Closed by veewee** 2022-12-20 13:36 UTC
