### ISSUE TITLE
Docker example from documentation not working

### ISSUE THREAD

**Issue by strikernl** [phpro/grumphp#758] opened 2020-04-14 13:55 UTC
| Q               | A
| --------------- | ---
| Version         | 1.8.0
| Bug?            | maybe
| New feature?    | no
| Question?       | no
| Documentation?  | yes
| Related tickets | #152

This example from the [documentation](https://github.com/phpro/grumphp/blob/master/doc/parameters.md) does not work for me in grumphp 1.8.0, it does not seem to resolve the variable `$(pwd)`:

```yaml
EXEC_GRUMPHP_COMMAND: 'docker run --rm -it -v $(pwd):/grumphp -w /grumphp webdevops/php:alpine'
```

I then run `git commit`.

First it complains about this: `the input device is not a TTY`, which is fixed by changing `-it` into `-i`.

Then it returns
```
docker: Error response from daemon: create $(pwd): "$(pwd)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```

Perhaps because it's put in single quotes in the resulting `pre-commit`?

```
'docker' 'run' '--rm' '-i' '-v' '$(pwd):/grumphp' '-w' '/grumphp' 'webdevops/php:alpine' 'vendor/phpro/grumphp/bin/grumphp' 'git:pre-commit' '--skip-success-output'
```

**Comment by veewee** [comment] 2020-05-26 13:51
Indeed, that looks like a bug.
We switched the type of the quotes a couple of times already, but we do neet to make sure that we can get things like `$(pwd)` to work.

In the meantime you could try to use docker-compose or define a named volume?

**Comment by veewee** [comment] 2020-05-26 14:07
Duplicate of #758

**Closed by veewee** 2020-05-26 14:07 UTC
Labels: bug

**Comment by strikernl** [comment] 2020-05-26 14:27
> Indeed, that looks like a bug.
> We switched the type of the quotes a couple of times already, but we do neet to make sure that we can get things like `$(pwd)` to work.
> 
> In the meantime you could try to use docker-compose or define a named volume?

Indeed a duplicate. I worked around it another way (by using an intermediate script). Just thought I'd report the bug ;)

Thanks!
