### ISSUE TITLE
Config option for phpcsfixer2 task is mandatory

### ISSUE THREAD

**Issue by pyrsmk** [phpro/grumphp#714] opened 2019-12-26 08:33 UTC
| Q               | A
| --------------- | ---
| Version         | 0.17.1
| Bug?            | maybe?
| New feature?    | no
| Question?       | no
| Documentation?  | probably?

When run without a `config` option, the phpcsfixer2 task would fail with:

```

In ConfigurationResolver.php line 582:

  [PhpCsFixer\ConfigurationException\InvalidConfigurationException (16)]
  For multiple paths config parameter is required.
````

When I fill the `config` option, the task is run without error.

Then, I assume this option is mandatory and a default option should be applied (`.php_cs.dist` seems accurate).

As stated in the docs, the default parameter is `null` and Grumphp should fallback to `.php_cs` (which is not a good practice, because it should be a non-commited local file).

**Comment by oallain** [comment] 2019-12-30 10:02
Hello @pyrsmk 

I can't reproduce your mistake.
Can you copy / paste your GrumPHP configuration?

**Comment by Taluu** [comment] 2020-01-09 17:15
Also have the problem, can reproduce with :

```yaml
parameters:
  tasks:
    phpcsfixer2:
      allow_risky: true
      verbose: false
      diff: true
      triggered_by: ['php']
```

But it seems it's something up to php-cs-fixer. I think that grumphp should be able if it's `null` to check for a `.php_cs` or `.php_cs.dist` files though.

**Comment by veewee** [comment] 2020-01-09 19:52
As with any tool, you need to find a configuration that works for you.
If you don't provide a config file, php-cs-fixer will try to find it automatically.
Instead of providing a file path, you can also provide a path in the --config option for php-cs-fixer.
See: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.16/src/Console/ConfigurationResolver.php#L565-L600

Guessing the file in GrumPHP is not something I'dd like to maintain. (We support a lot of tools, and we'dd like to keep tool specific logic inside the tool as much as possible.)

Does the solution above work for you?

**Comment by Taluu** [comment] 2020-01-09 21:13
Then you shouldn't allow `null` value for the `config` as grumphp uses that with multiple files anyway. I would be fine with this too.

**Comment by veewee** [comment] 2020-01-10 06:30
That would indeed be a valid solution: don't allow null and use current directory by default.
Feel free to provide a PR for this solution.

**Comment by veewee** [comment] 2020-08-27 08:13
Gonna close this one. Don't think we can add an easy solution within grumphp without having to maintain the burdon of detecting other tools config files.
The error message you receive from php-cs-fixer is clear enough and points out that you need to add a config file.

**Closed by veewee** 2020-08-27 08:13 UTC
Labels: enhancement, help wanted
