### ISSUE TITLE
Bug when i lunch git commit

### ISSUE THREAD

**Issue by EtewaZINSOU** [phpro/grumphp#770] opened 2020-06-04 10:45 UTC
| Q               | A
| --------------- | ---
| Version         |GrumPHP 0.18.1
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | yes/no

I want to commit message and i have this error

**My configuration**
```yaml
# grumphp.yml
# Please add a copy of your grumphp.yml file.
```
parameters:
    bin_dir: ./vendor/bin/
    stop_on_failure: true
    process_timeout: 3600
    tasks:
        #        clover_coverage:
        #            clover_file: /tmp/clover.xml
        #            level: 100
        git_blacklist:
          keywords:
            - "die("
            - "var_dump("
            - "dump("
            - " dd("
            - "exit;"
            - "console.log"
          triggered_by: [php, js, twig]
          metadata:
            priority: 3
        phpcs:
            standard: "vendor/escapestudios/symfony2-coding-standard/Symfony"
            warning_severity: 0
            ignore_patterns: ['docker-conf/*', '*/features/*', 'Kernel.php', 'AppCache.php', 'AppBundle.php', '*/Tests/', '*/Behat/*', '*/Configuration.php', 'config.php', 'SymfonyRequirements.php', '*/Migrations/*']
            metadata:
                priority: 1
        phpcpd:
          directory: ['src']
          exclude: ['docker-conf/', 'vendor', 'var', 'src/Migrations']
          names_exclude: []
          fuzzy: false
          min_lines: 3
          min_tokens: 70
          triggered_by: ['php']
        phpmd:
            exclude: ['docker-conf/', 'vendor', 'var', 'public', 'src/Migrations', 'src/Features']
            ruleset: ['./phpmd.xml']
            triggered_by: ['php']
        phpstan:
            autoload_file: ~
            configuration: ./phpstan.neon
            level: 0
            triggered_by: ['php']
        phpunitbridge:
            config_file: ~
            testsuite: ~
            group: []
            always_execute: true
        securitychecker:
            lockfile: ./composer.lock
            format: ~
            end_point: ~
            timeout: ~
            run_always: true
        git_commit_message:
            allow_empty_message: false
            enforce_capitalized_subject: true
            enforce_no_subject_punctuations: true
            enforce_single_lined_subject: true
            max_body_width: 1000
            max_subject_width: 71
            matchers:
                Must contain JIRA issue number: '/[Feature|Bugfix|Hotfix|Release] #PROD-\d+ :/'
            case_insensitive: true
            multiline: true
            additional_modifiers: ''
        git_branch_name:
            whitelist:
                - /[feature|bugfix|hotfix|release]\/PROD-\d+-\w+/
            blacklist:
                - "develop"
                - "master"
            additional_modifiers: ''
            allow_detached_head: false

**Steps to reproduce:**
```sh
# Generate empty folder
mkdir tmp
cd tmp
git init
echo "vendor" > .gitignore
pbpaste > grumphp.yml
composer require --dev phpro/grumphp

# Your actions
# Please add the steps on how to reproduce the issue here.
Lunch a command git commit
# Run GrumPHP:
git add -A && git commit -m"Test"
# or
./vendor/bin/grumphp run
```

**Result:**
```
# Please add the result of the run or git commit actions here.
```
In ParserBase.php line 85:
                                                                                               
  [Gitonomy\Git\Exception\RuntimeException]                                                    
  No match for regexp /diff --git (a\/.*) (b\/.*)\n/ Upcoming: diff --git c/README.md i/READM  
                                                                                               

Exception trace:
  at /Users/etewa/Sites/middleApi/vendor/gitonomy/gitlib/src/Gitonomy/Git/Parser/ParserBase.php:85
 Gitonomy\Git\Parser\ParserBase->consumeRegexp() at /Users/etewa/Sites/middleApi/vendor/gitonomy/gitlib/src/Gitonomy/Git/Parser/DiffParser.php:28
 Gitonomy\Git\Parser\DiffParser->doParse() at /Users/etewa/Sites/middleApi/vendor/gitonomy/gitlib/src/Gitonomy/Git/Parser/ParserBase.php:31
 Gitonomy\Git\Parser\ParserBase->parse() at /Users/etewa/Sites/middleApi/vendor/gitonomy/gitlib/src/Gitonomy/Git/Diff/Diff.php:53
 Gitonomy\Git\Diff\Diff::parse() at /Users/etewa/Sites/middleApi/vendor/gitonomy/gitlib/src/Gitonomy/Git/WorkingCopy.php:66
 Gitonomy\Git\WorkingCopy->getDiffStaged() at /Users/etewa/Sites/middleApi/vendor/phpro/grumphp/src/Locator/ChangedFiles.php:44
 GrumPHP\Locator\ChangedFiles->locateFromGitRepository() at /Users/etewa/Sites/middleApi/vendor/phpro/grumphp/src/Console/Command/Git/PreCommitCommand.php:85
 GrumPHP\Console\Command\Git\PreCommitCommand->getCommittedFiles() at /Users/etewa/Sites/middleApi/vendor/phpro/grumphp/src/Console/Command/Git/PreCommitCommand.php:66
 GrumPHP\Console\Command\Git\PreCommitCommand->execute() at /Users/etewa/Sites/middleApi/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /Users/etewa/Sites/middleApi/vendor/symfony/console/Application.php:929
 Symfony\Component\Console\Application->doRunCommand() at /Users/etewa/Sites/middleApi/vendor/symfony/console/Application.php:264
 Symfony\Component\Console\Application->doRun() at /Users/etewa/Sites/middleApi/vendor/symfony/console/Application.php:140
 Symfony\Component\Console\Application->run() at /Users/etewa/Sites/middleApi/vendor/phpro/grumphp/bin/grumphp:50
 {closure}() at /Users/etewa/Sites/middleApi/vendor/phpro/grumphp/bin/grumphp:51

git:pre-commit [--skip-success-output] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-c|--config CONFIG] [--] <command>

**Comment by veewee** [comment] 2020-07-13 12:55
Duplicate of #787. Continuing the conversation in that issue.

**Closed by veewee** 2020-07-13 12:55 UTC
